apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgCyhgNdA3J34ysq26r0aLJJ5ghcsL4QJEQdBUMDLm2rOJkzLE5AFxpJl9I1Nw6od6pW3kNFjJRyWkQrJwWXKaEexLOFX7shtL6HryIy73OvfimcOdGYMM3xtGKQK6Asos0TgtpqkWgwj31e2pnIOpyWR3lnTxnX9U8oRdq6tL4Mbt2+TFOl820c06xqFSgX4oqT/NZOPDT3w9GCls20hGU7ExgqSz3F+69wplemSUIqBJXeG1QjPcssJKIxItjJpv+tCjszloq/dPzRlApjCIF+FHReykk3AzvuoEtzpU16YQMLqFSe23gQkkMCFHHSHDP3dtbcVzLhZ3u2YEpAHbeUmMrC3Up1OYZMuQyAn0EWuuxufDbcTtz5Ifz5/p7AoLPjVm2mTR4O+4yi/c42d7CTHXxIfZHBTWJSU55kpxHj6I7vYYjMujYNPMn8r7dGrDs449S2dHp3yywTrKsInCX14ZR+QuTWpESeOk5a9ZGZUMcI3zepeLBhLLhxniRjQ+SiT/xPWXwq13spVVnl6YtsHvanOkJS/c5Y92rHTDNNCQbMh0pdE+q97JTtT6ymwfTE0az4oEj+IeZpUmZRGzYIfP9qY+BvLB1Kf9C0g+7bPjwpxFnFV4KgKYm6b6k2tVHFV9jVgctpSkBUcpi3Efa8eC1FgMOmv6oUbJ4U8EdMGc08+NFkN/nZDCtKixL39wp56s9YvqsLN18ThRY=
    username: AgBvnG29yBsQPcRQsRJigM982g68tclecWcSA0Qvp/GoXUc08mcZA/3dEY6CGS3ML7VyqlrlkEAcDtBUd4YzAvg5mLDMRD+U6xr7yp81Ebk2+r08xWRDYiQb/FVIlm2Xuxmr7hqPVs8mRseLOex6rIOQC3P7IDWuc0VWgQ94470wqvrbx9XFIYiRAMyDOFSQ/lKGWTnSgf+ZsvyDXXP55IlNYXB5gvOJDi6gt7aCBAD9cvkpkcPghZktsakaTSlShCrKoCMuZ72MO37IxgW4FWXzMGuLqqktzWOcZnA0x4AhKjrLQ1QwYA/pdbCXTJYupEG4vaFkKKjo1I0fZeshTJhV2SfNUal0QDfWRE9MekgyHvA+vVoSJV08foM2KlQBxiDL0aj5nwjpW0kWJN0HyPx6zi8DQlBH7DcvSTsnheHxS/I8KMwPOCVkjwmx7rinCS7nI74Xq4McUAECemEYUt//97H7decdyTsZ8oU4SAhvhcN7Tt7rw5ehs8sZf+JgmSObkTihrb0NmQz/1V2+P1rTdGkbrx5xhi6GPrl6ylPDsgVKY4UOl3bz5txWICbK102EeQs17207BEwkH7M81+D3AZrTytKlHVBw+r+i7EFfx77Fe2nUieZ8W/Mg08VzbhYwqEQSjBgH7kWnfeATnxEIcY1J5AHn39+f1VZBnijHn/bJWjOH7ORSWcoTUaJkjqH7Gwbe
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque
