apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
    containers:
      - name: secret-pod
        image: redis
        volumeMounts:
        - name: mysecret
          mountPath: “/etc/mysecret”
          readOnly: true
    volumes:
    - name: mysecret
      secret:
        secretName: mysecret
